version: 0.2

phases:
  pre_build:
    commands:
      - pip3 install Pillow
      - pip3 install markdown
  build:
    commands:
      - python _build/build_themes.py
      - python _build/build_pins.py
  post_build:
    commands:
      - git config user.email "codebuild@aws.amazon.com"
      - git config user.name "AWS CodeBuild"
      - git remote set-url origin https://Developer1510:Program0151@github.com/developer1510/Developer1510.github.io.git
      - git add */index.html
      - git add index.html
      - git commit -m [CodeBuild]
      - git push origin main
      - echo Build completed